//auth

export const SET_AUTH_LOADER = "SET_AUTH_LOADER";
export const SET_AUTH_VALIDATION_ERRORS = "SET_AUTH_VALIDATION_ERRORS";

export const SET_AUTH_SUCCESS = "SET_AUTH_SUCCESS";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const SET_AUTH_ERROR = "SET_AUTH_ERROR";
