//auth

export const SET_AUTH_LOADER = "SET_AUTH_LOADER";
export const SET_AUTH_VALIDATION_ERRORS = "SET_AUTH_VALIDATION_ERRORS";

export const SET_AUTH_SUCCESS = "SET_AUTH_SUCCESS";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const SET_AUTH_ERROR = "SET_AUTH_ERROR";
export const SET_AUTH_CLEAR = "SET_AUTH_CLEAR";

//ORGANIZATION
export const SET_ORGANIZATION_LOADER = "SET_ORGANIZATION_LOADER";
export const SET_ORGANIZATION_LIST = "SET_ORGANIZATION_LIST";
export const SET_ORGANIZATION_FAIL = "SET_ORGANIZATION_FAIL";
